/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 93
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_def = 1,
  anon_sym_main = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_COLON = 5,
  anon_sym_extern = 6,
  anon_sym_let = 7,
  anon_sym_in = 8,
  anon_sym_if = 9,
  anon_sym_else = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_COLON_EQ = 13,
  anon_sym_EQ = 14,
  anon_sym_COMMA = 15,
  anon_sym_true = 16,
  anon_sym_false = 17,
  anon_sym_BANG = 18,
  anon_sym_add1 = 19,
  anon_sym_sub1 = 20,
  anon_sym_newArray = 21,
  anon_sym_length = 22,
  anon_sym_isBool = 23,
  anon_sym_isInt = 24,
  anon_sym_isArray = 25,
  anon_sym_STAR = 26,
  anon_sym_PLUS = 27,
  anon_sym_DASH = 28,
  anon_sym_GT = 29,
  anon_sym_LT = 30,
  anon_sym_GT_EQ = 31,
  anon_sym_LT_EQ = 32,
  anon_sym_EQ_EQ = 33,
  anon_sym_BANG_EQ = 34,
  anon_sym_AMP_AMP = 35,
  anon_sym_PIPE_PIPE = 36,
  anon_sym_and = 37,
  sym_identifier = 38,
  sym_number = 39,
  sym_source_file = 40,
  sym_main = 41,
  sym_extern = 42,
  sym_externs = 43,
  sym_expr = 44,
  sym_bindings = 45,
  sym_binop_expr = 46,
  sym_prim1 = 47,
  sym_prim2 = 48,
  sym_decls = 49,
  sym_decl = 50,
  sym_ids = 51,
  sym_exprs = 52,
  sym_array = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_def] = "def",
  [anon_sym_main] = "main",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_extern] = "extern",
  [anon_sym_let] = "let",
  [anon_sym_in] = "in",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_BANG] = "!",
  [anon_sym_add1] = "add1",
  [anon_sym_sub1] = "sub1",
  [anon_sym_newArray] = "newArray",
  [anon_sym_length] = "length",
  [anon_sym_isBool] = "isBool",
  [anon_sym_isInt] = "isInt",
  [anon_sym_isArray] = "isArray",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_and] = "and",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_main] = "main",
  [sym_extern] = "extern",
  [sym_externs] = "externs",
  [sym_expr] = "expr",
  [sym_bindings] = "bindings",
  [sym_binop_expr] = "binop_expr",
  [sym_prim1] = "prim1",
  [sym_prim2] = "prim2",
  [sym_decls] = "decls",
  [sym_decl] = "decl",
  [sym_ids] = "ids",
  [sym_exprs] = "exprs",
  [sym_array] = "array",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_main] = anon_sym_main,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_add1] = anon_sym_add1,
  [anon_sym_sub1] = anon_sym_sub1,
  [anon_sym_newArray] = anon_sym_newArray,
  [anon_sym_length] = anon_sym_length,
  [anon_sym_isBool] = anon_sym_isBool,
  [anon_sym_isInt] = anon_sym_isInt,
  [anon_sym_isArray] = anon_sym_isArray,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_and] = anon_sym_and,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_main] = sym_main,
  [sym_extern] = sym_extern,
  [sym_externs] = sym_externs,
  [sym_expr] = sym_expr,
  [sym_bindings] = sym_bindings,
  [sym_binop_expr] = sym_binop_expr,
  [sym_prim1] = sym_prim1,
  [sym_prim2] = sym_prim2,
  [sym_decls] = sym_decls,
  [sym_decl] = sym_decl,
  [sym_ids] = sym_ids,
  [sym_exprs] = sym_exprs,
  [sym_array] = sym_array,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_main] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sub1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_newArray] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_length] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isBool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isInt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isArray] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_main] = {
    .visible = true,
    .named = true,
  },
  [sym_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_externs] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_bindings] = {
    .visible = true,
    .named = true,
  },
  [sym_binop_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_prim1] = {
    .visible = true,
    .named = true,
  },
  [sym_prim2] = {
    .visible = true,
    .named = true,
  },
  [sym_decls] = {
    .visible = true,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_ids] = {
    .visible = true,
    .named = true,
  },
  [sym_exprs] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_call = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_call] = "call",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_call, 0},
    {field_call, 1},
    {field_call, 2},
  [4] =
    {field_call, 0},
    {field_call, 1},
    {field_call, 2},
    {field_call, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '!', 86,
        '&', 2,
        '(', 65,
        ')', 66,
        '*', 101,
        '+', 102,
        ',', 80,
        '-', 103,
        ':', 67,
        '<', 105,
        '=', 79,
        '>', 104,
        '[', 75,
        ']', 76,
        'a', 15,
        'd', 18,
        'e', 31,
        'f', 10,
        'i', 25,
        'l', 19,
        'm', 11,
        'n', 20,
        's', 53,
        't', 42,
        '|', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 85,
        '(', 65,
        ')', 66,
        '=', 78,
        '[', 75,
        ']', 76,
        'a', 122,
        'd', 123,
        'f', 117,
        'i', 128,
        'l', 124,
        'n', 125,
        's', 146,
        't', 139,
        '+', 59,
        '-', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(152);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(110);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 4:
      if (lookahead == '1') ADVANCE(87);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(89);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(109);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(108);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(46);
      if (lookahead == 'B') ADVANCE(41);
      if (lookahead == 'I') ADVANCE(39);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(47);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 14:
      if (lookahead == 'b') ADVANCE(5);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(4);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(112);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'n') ADVANCE(71);
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(62);
      END_STATE();
    case 27:
      if (lookahead == 'g') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 'h') ADVANCE(93);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(48);
      if (lookahead == 'x') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(95);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(71);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(64);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 48:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 54:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 55:
      if (lookahead == 'w') ADVANCE(9);
      END_STATE();
    case 56:
      if (lookahead == 'y') ADVANCE(99);
      END_STATE();
    case 57:
      if (lookahead == 'y') ADVANCE(91);
      END_STATE();
    case 58:
      if (lookahead == '|') ADVANCE(111);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(152);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '!', 6,
        '&', 2,
        '(', 65,
        ')', 66,
        '*', 101,
        '+', 102,
        ',', 80,
        '-', 103,
        ':', 67,
        '<', 105,
        '=', 7,
        '>', 104,
        '[', 75,
        ']', 76,
        'a', 38,
        'e', 30,
        'i', 34,
        '|', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_main);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(108);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(109);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_add1);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_add1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_sub1);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_sub1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_newArray);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_newArray);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_length);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_length);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_isBool);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_isBool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_isInt);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_isInt);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_isArray);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_isArray);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(106);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(107);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(141);
      if (lookahead == 'B') ADVANCE(137);
      if (lookahead == 'I') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('C' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(73);
      if (lookahead == 's') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(145);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(130);
      if (lookahead == 't') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(147);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(152);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 60},
  [21] = {.lex_state = 60},
  [22] = {.lex_state = 60},
  [23] = {.lex_state = 60},
  [24] = {.lex_state = 60},
  [25] = {.lex_state = 60},
  [26] = {.lex_state = 60},
  [27] = {.lex_state = 60},
  [28] = {.lex_state = 60},
  [29] = {.lex_state = 60},
  [30] = {.lex_state = 60},
  [31] = {.lex_state = 60},
  [32] = {.lex_state = 60},
  [33] = {.lex_state = 60},
  [34] = {.lex_state = 60},
  [35] = {.lex_state = 60},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 60},
  [43] = {.lex_state = 60},
  [44] = {.lex_state = 60},
  [45] = {.lex_state = 60},
  [46] = {.lex_state = 60},
  [47] = {.lex_state = 60},
  [48] = {.lex_state = 60},
  [49] = {.lex_state = 60},
  [50] = {.lex_state = 60},
  [51] = {.lex_state = 60},
  [52] = {.lex_state = 60},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_main] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_add1] = ACTIONS(1),
    [anon_sym_sub1] = ACTIONS(1),
    [anon_sym_newArray] = ACTIONS(1),
    [anon_sym_length] = ACTIONS(1),
    [anon_sym_isBool] = ACTIONS(1),
    [anon_sym_isInt] = ACTIONS(1),
    [anon_sym_isArray] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(87),
    [sym_main] = STATE(90),
    [sym_extern] = STATE(53),
    [sym_externs] = STATE(66),
    [anon_sym_def] = ACTIONS(3),
    [anon_sym_extern] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(42), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    STATE(76), 1,
      sym_exprs,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [60] = 17,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    ACTIONS(29), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    STATE(89), 1,
      sym_exprs,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [120] = 16,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(42), 1,
      sym_expr,
    STATE(55), 1,
      sym_exprs,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [177] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(50), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [231] = 16,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(27), 1,
      sym_binop_expr,
    STATE(34), 1,
      sym_array,
    STATE(52), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [287] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(47), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [341] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(51), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [395] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(48), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [449] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(23), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [503] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(46), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [557] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(21), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [611] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(49), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [665] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(43), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [719] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(25), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [773] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(44), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [827] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(26), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [881] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(45), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [935] = 15,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_BANG,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_number,
    STATE(20), 1,
      sym_expr,
    STATE(57), 1,
      sym_decls,
    STATE(58), 1,
      sym_decl,
    STATE(75), 1,
      sym_prim1,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 2,
      sym_binop_expr,
      sym_array,
    ACTIONS(23), 7,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
  [989] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(31), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_and,
  [1031] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(49), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_and,
  [1073] = 3,
    ACTIONS(55), 1,
      anon_sym_COLON_EQ,
    ACTIONS(53), 3,
      anon_sym_COLON,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(51), 17,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1101] = 4,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(59), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(57), 17,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1131] = 3,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(65), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(61), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1159] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(51), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_and,
  [1201] = 4,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(69), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(67), 17,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1231] = 2,
    ACTIONS(73), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1256] = 2,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1281] = 2,
    ACTIONS(81), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(79), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1306] = 2,
    ACTIONS(85), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(83), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1331] = 2,
    ACTIONS(89), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(87), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1356] = 2,
    ACTIONS(59), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(57), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1381] = 2,
    ACTIONS(65), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(61), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1406] = 2,
    ACTIONS(93), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(91), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1431] = 2,
    ACTIONS(97), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(95), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_else,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
  [1456] = 2,
    ACTIONS(101), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG,
      sym_number,
    ACTIONS(99), 13,
      anon_sym_def,
      anon_sym_let,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
      sym_identifier,
  [1478] = 2,
    ACTIONS(101), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG,
      sym_number,
    ACTIONS(99), 13,
      anon_sym_def,
      anon_sym_let,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
      sym_identifier,
  [1500] = 2,
    ACTIONS(101), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG,
      sym_number,
    ACTIONS(99), 13,
      anon_sym_def,
      anon_sym_let,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
      sym_identifier,
  [1522] = 2,
    ACTIONS(101), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG,
      sym_number,
    ACTIONS(99), 13,
      anon_sym_def,
      anon_sym_let,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
      sym_identifier,
  [1544] = 2,
    ACTIONS(101), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG,
      sym_number,
    ACTIONS(99), 13,
      anon_sym_def,
      anon_sym_let,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
      sym_identifier,
  [1566] = 2,
    ACTIONS(101), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG,
      sym_number,
    ACTIONS(99), 13,
      anon_sym_def,
      anon_sym_let,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      anon_sym_add1,
      anon_sym_sub1,
      anon_sym_newArray,
      anon_sym_length,
      anon_sym_isBool,
      anon_sym_isInt,
      anon_sym_isArray,
      sym_identifier,
  [1588] = 11,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(103), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1627] = 11,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(107), 1,
      anon_sym_in,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1665] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(111), 2,
      anon_sym_in,
      anon_sym_and,
  [1701] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(113), 2,
      anon_sym_in,
      anon_sym_and,
  [1737] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1772] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(117), 1,
      anon_sym_COLON,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1807] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1842] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(121), 1,
      anon_sym_else,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1877] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1912] = 10,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(125), 1,
      anon_sym_RBRACK,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1947] = 9,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym_AMP_AMP,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    STATE(10), 1,
      sym_prim2,
    ACTIONS(37), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(43), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1979] = 4,
    ACTIONS(5), 1,
      anon_sym_extern,
    ACTIONS(127), 1,
      anon_sym_def,
    STATE(53), 1,
      sym_extern,
    STATE(70), 1,
      sym_externs,
  [1992] = 3,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(131), 1,
      sym_identifier,
    STATE(73), 1,
      sym_ids,
  [2002] = 1,
    ACTIONS(133), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [2007] = 2,
    ACTIONS(135), 1,
      anon_sym_def,
    STATE(60), 1,
      sym_decl,
  [2014] = 2,
    ACTIONS(137), 1,
      anon_sym_in,
    ACTIONS(139), 1,
      anon_sym_and,
  [2021] = 1,
    ACTIONS(141), 2,
      anon_sym_in,
      anon_sym_and,
  [2026] = 2,
    ACTIONS(131), 1,
      sym_identifier,
    STATE(77), 1,
      sym_ids,
  [2033] = 1,
    ACTIONS(143), 2,
      anon_sym_in,
      anon_sym_and,
  [2038] = 2,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    ACTIONS(147), 1,
      anon_sym_COMMA,
  [2045] = 2,
    ACTIONS(131), 1,
      sym_identifier,
    STATE(85), 1,
      sym_ids,
  [2052] = 1,
    ACTIONS(149), 2,
      anon_sym_def,
      anon_sym_extern,
  [2057] = 2,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(88), 1,
      sym_bindings,
  [2064] = 2,
    ACTIONS(151), 1,
      sym_identifier,
    STATE(69), 1,
      sym_bindings,
  [2071] = 2,
    ACTIONS(3), 1,
      anon_sym_def,
    STATE(71), 1,
      sym_main,
  [2078] = 1,
    ACTIONS(153), 1,
      anon_sym_COLON,
  [2082] = 1,
    ACTIONS(155), 1,
      anon_sym_EQ,
  [2086] = 1,
    ACTIONS(157), 1,
      anon_sym_in,
  [2090] = 1,
    ACTIONS(159), 1,
      anon_sym_def,
  [2094] = 1,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
  [2098] = 1,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
  [2102] = 1,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
  [2106] = 1,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
  [2110] = 1,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
  [2114] = 1,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
  [2118] = 1,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
  [2122] = 1,
    ACTIONS(175), 1,
      anon_sym_COLON,
  [2126] = 1,
    ACTIONS(177), 1,
      anon_sym_LPAREN,
  [2130] = 1,
    ACTIONS(179), 1,
      anon_sym_LPAREN,
  [2134] = 1,
    ACTIONS(181), 1,
      sym_identifier,
  [2138] = 1,
    ACTIONS(183), 1,
      anon_sym_COLON,
  [2142] = 1,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
  [2146] = 1,
    ACTIONS(187), 1,
      anon_sym_COLON,
  [2150] = 1,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
  [2154] = 1,
    ACTIONS(191), 1,
      sym_identifier,
  [2158] = 1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [2162] = 1,
    ACTIONS(195), 1,
      anon_sym_in,
  [2166] = 1,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
  [2170] = 1,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
  [2174] = 1,
    ACTIONS(201), 1,
      anon_sym_main,
  [2178] = 1,
    ACTIONS(203), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 60,
  [SMALL_STATE(4)] = 120,
  [SMALL_STATE(5)] = 177,
  [SMALL_STATE(6)] = 231,
  [SMALL_STATE(7)] = 287,
  [SMALL_STATE(8)] = 341,
  [SMALL_STATE(9)] = 395,
  [SMALL_STATE(10)] = 449,
  [SMALL_STATE(11)] = 503,
  [SMALL_STATE(12)] = 557,
  [SMALL_STATE(13)] = 611,
  [SMALL_STATE(14)] = 665,
  [SMALL_STATE(15)] = 719,
  [SMALL_STATE(16)] = 773,
  [SMALL_STATE(17)] = 827,
  [SMALL_STATE(18)] = 881,
  [SMALL_STATE(19)] = 935,
  [SMALL_STATE(20)] = 989,
  [SMALL_STATE(21)] = 1031,
  [SMALL_STATE(22)] = 1073,
  [SMALL_STATE(23)] = 1101,
  [SMALL_STATE(24)] = 1131,
  [SMALL_STATE(25)] = 1159,
  [SMALL_STATE(26)] = 1201,
  [SMALL_STATE(27)] = 1231,
  [SMALL_STATE(28)] = 1256,
  [SMALL_STATE(29)] = 1281,
  [SMALL_STATE(30)] = 1306,
  [SMALL_STATE(31)] = 1331,
  [SMALL_STATE(32)] = 1356,
  [SMALL_STATE(33)] = 1381,
  [SMALL_STATE(34)] = 1406,
  [SMALL_STATE(35)] = 1431,
  [SMALL_STATE(36)] = 1456,
  [SMALL_STATE(37)] = 1478,
  [SMALL_STATE(38)] = 1500,
  [SMALL_STATE(39)] = 1522,
  [SMALL_STATE(40)] = 1544,
  [SMALL_STATE(41)] = 1566,
  [SMALL_STATE(42)] = 1588,
  [SMALL_STATE(43)] = 1627,
  [SMALL_STATE(44)] = 1665,
  [SMALL_STATE(45)] = 1701,
  [SMALL_STATE(46)] = 1737,
  [SMALL_STATE(47)] = 1772,
  [SMALL_STATE(48)] = 1807,
  [SMALL_STATE(49)] = 1842,
  [SMALL_STATE(50)] = 1877,
  [SMALL_STATE(51)] = 1912,
  [SMALL_STATE(52)] = 1947,
  [SMALL_STATE(53)] = 1979,
  [SMALL_STATE(54)] = 1992,
  [SMALL_STATE(55)] = 2002,
  [SMALL_STATE(56)] = 2007,
  [SMALL_STATE(57)] = 2014,
  [SMALL_STATE(58)] = 2021,
  [SMALL_STATE(59)] = 2026,
  [SMALL_STATE(60)] = 2033,
  [SMALL_STATE(61)] = 2038,
  [SMALL_STATE(62)] = 2045,
  [SMALL_STATE(63)] = 2052,
  [SMALL_STATE(64)] = 2057,
  [SMALL_STATE(65)] = 2064,
  [SMALL_STATE(66)] = 2071,
  [SMALL_STATE(67)] = 2078,
  [SMALL_STATE(68)] = 2082,
  [SMALL_STATE(69)] = 2086,
  [SMALL_STATE(70)] = 2090,
  [SMALL_STATE(71)] = 2094,
  [SMALL_STATE(72)] = 2098,
  [SMALL_STATE(73)] = 2102,
  [SMALL_STATE(74)] = 2106,
  [SMALL_STATE(75)] = 2110,
  [SMALL_STATE(76)] = 2114,
  [SMALL_STATE(77)] = 2118,
  [SMALL_STATE(78)] = 2122,
  [SMALL_STATE(79)] = 2126,
  [SMALL_STATE(80)] = 2130,
  [SMALL_STATE(81)] = 2134,
  [SMALL_STATE(82)] = 2138,
  [SMALL_STATE(83)] = 2142,
  [SMALL_STATE(84)] = 2146,
  [SMALL_STATE(85)] = 2150,
  [SMALL_STATE(86)] = 2154,
  [SMALL_STATE(87)] = 2158,
  [SMALL_STATE(88)] = 2162,
  [SMALL_STATE(89)] = 2166,
  [SMALL_STATE(90)] = 2170,
  [SMALL_STATE(91)] = 2174,
  [SMALL_STATE(92)] = 2178,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 7, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop_expr, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop_expr, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop_expr, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop_expr, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 6, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 6, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop_expr, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop_expr, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop_expr, 4, 0, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop_expr, 4, 0, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop_expr, 3, 0, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop_expr, 3, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop_expr, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binop_expr, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prim2, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim2, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bindings, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 6, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 7, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main, 7, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_externs, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decls, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decls, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ids, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 5, 0, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_externs, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim1, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ids, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [193] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bindings, 5, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_snake(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "snake",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 4,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
